### ISSUE TITLE
 Map navigation with 4 agents

### ISSUE THREAD

**Issue by chen12345678910** [VIS4ROB-lab/multi_robot_coordination#6]
There is a problem in the terminal when running the following command.
$ roslaunch multi_robot_simulation vins_sim.launch agent_id:=0
$ roslaunch agent_local_planner agent_mapping_four_sim_0.launch
$ roslaunch multi_robot_simulation vins_sim.launch agent_id:=1
$ roslaunch agent_local_planner agent_mapping_four_sim_1.launch
![2022-05-30 17-07-22 的屏幕截图](https://user-images.githubusercontent.com/73885580/171008857-6d4d449b-df3f-4328-ab78-1907f2d3b663.png)
![2022-05-30 17-07-25 的屏幕截图](https://user-images.githubusercontent.com/73885580/171008866-cdfa42ef-af46-49b8-943d-3077354e93dd.png)

**Comment by lucaBartolomei** [comment]
Hi,
there seems to be a problem with the flow of data from the simulator to VINS (and consequently, with TFs). 
- Did you follow the [installation process](https://github.com/VIS4ROB-lab/multi_robot_coordination#installation-instructions) step-by-step?
- Did the installation process complete successfully? 
- When you run the simulation, are images and IMU messages published correctly? (you can check this, e.g. using `rostopic echo`)

I would also suggest to try to kill all the ROS-related processes, kill all the gazebo processes and re-run the commands.

**Comment by chen12345678910** [comment]
Thank you for your reply.
My installation was successful
![2022-05-31 09-55-38 的屏幕截图](https://user-images.githubusercontent.com/73885580/171131959-600e102d-4126-420c-89f4-60d52fd89a8f.png)
.
 images and IMU messages published correctly
![2022-05-31 21-36-50 的屏幕截图](https://user-images.githubusercontent.com/73885580/171186737-52542c97-fa03-41ba-94d0-f45a4871db5e.png)
.
But I still made the above mistake

**Comment by lucaBartolomei** [comment]
It seems that this is more linked to the image stream. Can you see the images (e.g. via `rqt_image_view`)? If you can see them correctly, check if `vins` is receiving them (e.g. `rosnode info`).

**Comment by chen12345678910** [comment]
rqt_image_view
![2022-06-01 09-22-25 的屏幕截图](https://user-images.githubusercontent.com/73885580/171311197-971f5300-f5d2-4d72-882d-35601f1e4c56.png)
rosnode info /firefly_0/vins_estimator_0
Node [/firefly_0/vins_estimator_0]
Publications: 
 * /firefly_0/vins_estimator_0/camera_pose [nav_msgs/Odometry]
 * /firefly_0/vins_estimator_0/camera_pose_visual [visualization_msgs/MarkerArray]
 * /firefly_0/vins_estimator_0/extrinsic [nav_msgs/Odometry]
 * /firefly_0/vins_estimator_0/history_cloud [sensor_msgs/PointCloud]
 * /firefly_0/vins_estimator_0/imu_propagate [nav_msgs/Odometry]
 * /firefly_0/vins_estimator_0/key_poses [visualization_msgs/Marker]
 * /firefly_0/vins_estimator_0/keyframe_point [sensor_msgs/PointCloud]
 * /firefly_0/vins_estimator_0/keyframe_pose [nav_msgs/Odometry]
 * /firefly_0/vins_estimator_0/odometry [nav_msgs/Odometry]
 * /firefly_0/vins_estimator_0/path [nav_msgs/Path]
 * /firefly_0/vins_estimator_0/point_cloud [sensor_msgs/PointCloud]
 * /firefly_0/vins_estimator_0/relo_relative_pose [nav_msgs/Odometry]
 * /firefly_0/vins_estimator_0/relocalization_path [nav_msgs/Path]
 * /firefly_0/vins_estimator_0/transform [geometry_msgs/TransformStamped]
 * /rosout [rosgraph_msgs/Log]
 * /tf [tf2_msgs/TFMessage]

Subscriptions: 
 * /clock [rosgraph_msgs/Clock]
 * /firefly_0/feature_tracker_0/feature [sensor_msgs/PointCloud]
 * /firefly_0/feature_tracker_0/restart [std_msgs/Bool]
 * /firefly_0/vi_sensor/imu [sensor_msgs/Imu]

Services: 
 * /firefly_0/vins_estimator_0/get_loggers
 * /firefly_0/vins_estimator_0/set_logger_level


contacting node http://chen-Victus-by-HP-Laptop-16-d0xxx:37447/ ...
Pid: 21319
Connections:
 * topic: /rosout
    * to: /rosout
    * direction: outbound (55399 - 127.0.0.1:41674) [19]
    * transport: TCPROS
 * topic: /firefly_0/vins_estimator_0/transform
    * to: /firefly_0/pose_sensor_vins_0
    * direction: outbound (55399 - 127.0.0.1:41688) [12]
    * transport: TCPROS
 * topic: /firefly_0/vins_estimator_0/keyframe_pose
    * to: /firefly_0/pose_graph_0
    * direction: outbound (55399 - 127.0.0.1:41718) [11]
    * transport: TCPROS
 * topic: /firefly_0/vins_estimator_0/keyframe_point
    * to: /firefly_0/pose_graph_0
    * direction: outbound (55399 - 127.0.0.1:41716) [10]
    * transport: TCPROS
 * topic: /tf
    * to: /rviz
    * direction: outbound (55399 - 127.0.0.1:41960) [15]
    * transport: TCPROS
 * topic: /tf
    * to: /pointcloud_filter_node_0
    * direction: outbound (55399 - 127.0.0.1:42150) [17]
    * transport: TCPROS
 * topic: /tf
    * to: /pointcloud_filter_node_1
    * direction: outbound (55399 - 127.0.0.1:45728) [18]
    * transport: TCPROS
 * topic: /clock
    * to: /gazebo (http://chen-Victus-by-HP-Laptop-16-d0xxx:35875/)
    * direction: inbound (38354 - chen-Victus-by-HP-Laptop-16-d0xxx:39347) [13]
    * transport: TCPROS
 * topic: /firefly_0/vi_sensor/imu
    * to: /gazebo (http://chen-Victus-by-HP-Laptop-16-d0xxx:35875/)
    * direction: inbound (38358 - chen-Victus-by-HP-Laptop-16-d0xxx:39347) [21]
    * transport: TCPROS
 * topic: /firefly_0/feature_tracker_0/feature
    * to: /firefly_0/feature_tracker_0 (http://chen-Victus-by-HP-Laptop-16-d0xxx:37935/)
    * direction: inbound (49118 - chen-Victus-by-HP-Laptop-16-d0xxx:49427) [20]
    * transport: TCPROS
 * topic: /firefly_0/feature_tracker_0/restart
    * to: /firefly_0/feature_tracker_0 (http://chen-Victus-by-HP-Laptop-16-d0xxx:37935/)
    * direction: inbound (49122 - chen-Victus-by-HP-Laptop-16-d0xxx:49427) [22]
    * transport: TCPROS

**Comment by lucaBartolomei** [comment]
It seems that all the connections are correct. If you are running 4 agents (as the title of the issue suggests), maybe your PC cannot cope with the computational load. Does the same error appear when you run only 1 agent?

**Comment by chen12345678910** [comment]
This is what happens when I run 1 agent.
first,roslaunch multi_robot_simulation mav_sim_chemical_plant_four.launch.Model loaded successfully.
roslaunch multi_robot_simulation vins_sim.launch agent_id:=0
![2022-06-05 12-31-10 的屏幕截图](https://user-images.githubusercontent.com/73885580/172035252-5bd78690-97e1-4a8a-98f5-4b65a745de64.png)
roslaunch agent_local_planner agent_mapping_four_sim_0.launch
![2022-06-05 12-31-46 的屏幕截图](https://user-images.githubusercontent.com/73885580/172035263-97cd036f-7a4f-46df-a056-d65531f4e916.png)

**Comment by chen12345678910** [comment]
I guess something is wrong with vins.

**Comment by lucaBartolomei** [comment]
Can you get an odometry estimate from VINS? If the robot moves, does this estimate make sense? It is weird that the 'dt' is negative. You could also try not to estimate it (changing [this parameter](https://github.com/VIS4ROB-lab/multi_robot_coordination/blob/8c86a5c7ffbd73dcce1cb77495edeb7e1f8b39e6/multi_robot_simulation/cfg/vins/vins_sim_agent_0.yaml#L82)).

**Comment by chen12345678910** [comment]
After modificatio.
![2022-06-06 15-47-25 的屏幕截图](https://user-images.githubusercontent.com/73885580/172118551-3deaea31-2989-4196-9437-c73ed95e3dc0.png)
n
 roslaunch agent_local_planner agent_mapping_four_sim_0.launch
[error] [1654500155.025305940] appears: parameters failed to load
![2022-06-06 15-29-45 的屏幕截图](https://user-images.githubusercontent.com/73885580/172118806-def21087-b4f9-4d11-bb7e-fc9bfcd43a2e.png)

**Comment by lucaBartolomei** [comment]
So is the problem with VINS solved? If the error now comes from the launch file `agent_mapping_four_sim_0.launch`, most likely it's a problem with `pcl_fusion` or `pointcloud_filter_node`. Could you backtrack where the error is coming from?

**Comment by lucaBartolomei** [comment]
Closing this issue because it's inactive - feel free to re-open it in case you need additional help.
