### ISSUE TITLE
could this framework run on popular datasets, for example on the EuRoC datasets and make voxblox map finally?

### ISSUE THREAD

**Issue by selfInnovator** [VIS4ROB-lab/multi_robot_coordination#7]

**Comment by lucaBartolomei** [comment]
Hi,

I am not sure if I understood your question correctly. What are you trying to do exactly? 

Here there are some general suggestions:
- If you want to replicate some of our results, you could run the pose graph & mapping pipeline as described in [these instructions](https://github.com/VIS4ROB-lab/pose_graph_backend#1-euroc-dataset). 
- If instead you want to use the original EuRoC rosbags, you can take a look at [this issue](https://github.com/VIS4ROB-lab/pose_graph_backend/issues/3).

I hope this helps.

**Comment by selfInnovator** [comment]
thanks for your answer, i also have a question:
can the client( front end) be switched to another VIO system,for example orbslam3, in condition of other parts are not modified?

**Comment by lucaBartolomei** [comment]
In theory this should be possible, as long as the back-end is provided with all the information it needs. 

However, I would expect this to require some work, as we use custom message types in our pipeline. You can find more information about ROS topics [here](https://github.com/VIS4ROB-lab/pose_graph_backend#topics).

**Comment by selfInnovator** [comment]
OK ，thanks very much，and i also ask a question；
can this whole framework run on Ubuntu 20.04？

**Comment by lucaBartolomei** [comment]
It has never been tested on Ubuntu 20.04, but migrating from Ubuntu 18.04 to 20.04 shouldn't be extremely difficult.

However:
- I think the biggest problem would be the adaptation of VINS-client-server / pose graph backend, as it is based on OpenCV 3, while on Ubuntu 20.04 the default is OpenCV 4. This problem could be solved by using meta packages in the catkin workspace, e.g. [opencv3_catkin](https://github.com/ethz-asl/opencv3_catkin), which are already cloned by our installation scripts [here](https://github.com/VIS4ROB-lab/multi_robot_coordination/blob/8c86a5c7ffbd73dcce1cb77495edeb7e1f8b39e6/dependencies_https.rosinstall#L7).
- The other open point is the version of Gazebo used for simulation. I am not sure if there had been major changes there, but the pipeline should be properly tested with a new Gazebo version.

In general, adding support for Ubuntu 20.04 would be great. I was planning to work on it, but never had the time. If you ever have a working version (even for just some of the packages you are interested in), please open a pull request and we can add this. I can even help with that, but from January 2023.

**Comment by lucaBartolomei** [comment]
I will close this because of inactivity - feel free to re-open it.
